### ISSUE TITLE
Repeated AutoBody additions cause StackOverflow

### ISSUE THREAD

**Issue by KunalGhoshGitHub** [weymouth/WaterLily.jl#88] opened 2023-12-30 16:36 UTC
Respected sir,

I am facing an issue while using this code. Actually, when I am using more than a certain number (6) of members as "sdf" in a code, it gives me "StackOverflowError". Can you please help me figure out any possible solution for it?

Thank you for your time and consideration.

Yours sincerely,
Kunal Ghosh

**Comment by weymouth** [comment] 2023-12-30 17:27
Can you make a very small example that replicates the error?

**Comment by KunalGhoshGitHub** [comment] 2024-01-01 05:33
Yes sir. 

Firstly, thank you for your time. I have attached a code to reproduce the error. Also, I have pasted the error at the end.

**Code:** 

using WaterLily
using Plots; gr()
using StaticArrays
include("TwoD_plots.jl")

let 
    # parameters
    ϵ=0.5
    thk=2ϵ+√2
    Re = 250; 
    U = 1
    p = 5; 
    L = 2^p
    radius = L/2
    
    p0=radius/3; v0=0.1*L; a0=0; t0=0
        
    function sdf_1(x,t)
        √sum(abs2,(1L >= x[1] .> 0L) ? (x[2]) : x ) - thk/2
    end
    
    function map_1(x,t)
        x = (x - SA[4L,4L])
        α = 0*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_2(x,t)
        x = (x - SA[4L,4L])
        α = 1*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_3(x,t)
        x = (x - SA[4L,4L])
        α = 2*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_4(x,t)
        x = (x - SA[4L,4L])
        α = 3*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_5(x,t)
        x = (x - SA[4L,4L])
        α = 4*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_6(x,t)
        x = (x - SA[4L,4L])
        α = 5*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_7(x,t)
        x = (x - SA[4L,4L])
        α = 6*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_8(x,t)
        x = (x - SA[4L,4L])
        α = 7*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_9(x,t)
        x = (x - SA[4L,4L])
        α = 8*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    function map_10(x,t)
        x = (x - SA[4L,4L])
        α = 9*pi/10
        R = SA[cos(α) sin(α); -sin(α) cos(α)]
        x = R*x
    end

    link_1 = AutoBody(sdf_1,map_1)
    link_2 = AutoBody(sdf_1,map_2)
    link_3 = AutoBody(sdf_1,map_3)
    link_4 = AutoBody(sdf_1,map_4)
    link_5 = AutoBody(sdf_1,map_5)
    link_6 = AutoBody(sdf_1,map_6)
    link_7 = AutoBody(sdf_1,map_7)
    link_8 = AutoBody(sdf_1,map_8)
    link_9 = AutoBody(sdf_1,map_9)
    link_10 = AutoBody(sdf_1,map_10)
    
    
    all_link = link_1 + link_2 + link_3 + link_4  + link_5 + link_6 + link_7 + link_8 + link_9 + link_10
    
    # generate sim
    sim = Simulation((10L,10L), (U,0), radius; ν=U*radius/Re, body=all_link)

    # get start time
    duration=1; step=0.1; t₀=round(sim_time(sim))

    @time @gif for tᵢ in range(t₀,t₀+duration;step)

        # update until time tᵢ in the background
        t = sum(sim.flow.Δt[1:end-1])
        while t < tᵢ*sim.L/sim.U

            # measure body
            measure!(sim,t)

            # update flow
            mom_step!(sim.flow,sim.pois)
            
            Δt = sim.flow.Δt[end]
            p0 += Δt*v0 
            t0 = t; t += Δt
        end

        # plot vorticity
        @inside sim.flow.σ[I] = WaterLily.curl(3,I,sim.flow.u)*sim.L/sim.U
        flood(sim.flow.σ; shift=(-0.5,-0.5),clims=(-5,5))
        body_plot!(sim); plot!(title="tU/L $tᵢ")
        
        # print time step
        println("tU/L=",round(tᵢ,digits=4),", Δt=",round(sim.flow.Δt[end],digits=3))
    end
end

**Error:**

StackOverflowError:

Stacktrace:
 [1] afoldl(::typeof(+), ::AutoBody{WaterLily.var"#comp#153"{Bool, WaterLily.var"#sdf#157"{AutoBody{WaterLily.var"#comp#153"{Bool, WaterLily.var"#sdf#157"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_3#13"{Int64}}, var"#map_3#13"{Int64}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, WaterLily.var"#sdf#157"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_3#13"{Int64}}, var"#map_3#13"{Int64}}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, WaterLily.var"#sdf#157"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}}, WaterLily.var"#map#156"{AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}}}, AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_3#13"{Int64}}, var"#map_3#13"{Int64}}}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_4#14"{Int64}}, var"#map_4#14"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_5#15"{Int64}}, var"#map_5#15"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_6#16"{Int64}}, var"#map_6#16"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_7#17"{Int64}}, var"#map_7#17"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_8#18"{Int64}}, var"#map_8#18"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_9#19"{Int64}}, var"#map_9#19"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_10#20"{Int64}}, var"#map_10#20"{Int64}})
   @ Base ./operators.jl:531
 [2] +(::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_1#11"{Int64}}, var"#map_1#11"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_2#12"{Int64}}, var"#map_2#12"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_3#13"{Int64}}, var"#map_3#13"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_4#14"{Int64}}, var"#map_4#14"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_5#15"{Int64}}, var"#map_5#15"{Int64}}, ::AutoBody{WaterLily.var"#comp#153"{Bool, var"#sdf_1#10"{Int64, Float64}, var"#map_6#16"{Int64}}, var"#map_6#16"{Int64}}, ::Vararg{Any})
   @ Base ./operators.jl:578
 [3] top-level scope
   @ ./In[2]:100

**Comment by weymouth** [comment] 2024-01-01 08:23
So the error only happens when you have 10 bodies, not 9 or 8? And the plotting stuff is required to trigger the error? I doubt it.

If possible, can you please try reducing the code down to the minimal amount required to reproduce the error?

**Comment by weymouth** [comment] 2024-01-01 10:56
Here is an example that seems to get to the heart of the problem...
```julia
using WaterLily
N = 64
circ(x,t) = √sum(abs2,x)-N/8
body = AutoBody(circ,(x,t)->x-N*rand(2))
for i in 2:10
    body += AutoBody(circ,(x,t)->x-N*rand(2))
    @show i, sizeof(body)
end
```
On my laptop, this gives:
```
2,7
3,25
4,79
5,241
6,727
7,2185
8,6559
9,19681
10,59047
11,177145
12,531439
13,1594321
ERROR: StackOverflowError:
```
So the problem is that the compound function is growing (exponentially?) as more bodies are added on.  It's not obvious to me why this is happening. You can see the code here, and while it isn't complicated, it clearly doesn't scale up correctly.
https://github.com/weymouth/WaterLily.jl/blob/ecad1ca8ae26542e404d1209a19faa7d2562faf8/src/AutoBody.jl#L22-L26

Perhaps one of the other developers has a suggestion for a way to improve this function...

**Comment by KunalGhoshGitHub** [comment] 2024-01-01 11:10
Ok thank you

**Comment by weymouth** [comment] 2024-01-01 11:15
For the case where all the bodies have the same `sdf` (like in my example) we would like the code to do something like this
```julia
using WaterLily
circ(x,t) = √sum(abs2,x)-1/8
maps = ntuple(i-> (x,t)->x-rand(2), 20)
min_map(x,t)=argmin(m->circ(m(x,t),t),maps)(x,t)
body = AutoBody(circ,min_map)
sizeof(body)
measure(body,rand(2),0)
```
This keeps the code very small no matter how many bodies you use. You should be able to use the approach above as a work around until the bug in the code base is fixed.

**Comment by KunalGhoshGitHub** [comment] 2024-01-01 11:24
OK thank you for the help. I will be using this approach then.

**Comment by weymouth** [comment] 2024-01-01 11:32
Make sure to test it out carefully. I haven't done anything except check that it doesn't blow up. ;-)

**Comment by b-fg** [comment] 2024-01-08 14:07
We should do this in a loop, instead of recursion. Looking into it..

**Comment by b-fg** [comment] 2024-01-20 13:20
Using this branch https://github.com/weymouth/WaterLily.jl/pull/95 this original issue can now be fixed with
```
all_link = Bodies([link_1, link_2, link_3, link_4, link_5, link_6, link_7, link_8, link_9, link_10], +)
```

**Closed** 2024-02-17 15:25 UTC
Labels: bug, help wanted, good first issue
